
      export const punkHourExp = [
        [
          "Intro/Masacre Animal - ESTIGIA",
          "Lucha  - ESTIGIA",
          "Stay Punk  - ESTIGIA",
          "Manipuladxs  - ESTIGIA",
          "España de mierda  - ESTIGIA",
          "A look of tomorrow  - ESTIGIA",
          "Guerras Inutiles  - ESTIGIA",
          "En un lado o en otro  - ESTIGIA",
          "Ultrabasura  - ESTIGIA",
          "Golpe al Estado - ESTIGIA",
          "Alerta Antifascista - ESTIGIA",

          "Nigeria - Ataque de Caspa",
          "Lalala - Ataque de Caspa",
          "La pesca - Ataque de Caspa",
          "Cronica China - Ataque de Caspa",
          "La Militar - Ataque de Caspa",
          "Viaje a Egipto - Ataque de Caspa",

            "Odio - Puñal",
            "Reniego del Punk - Puñal",  
            "Cicatrices - Puñal",  
            "Jodido Personaje - Puñal", 
            "Amor - Puñal",
            "Carrera Criminal - Puñal",
            "Yo no he estado ahí  - Puñal",
            "Nadie te Puede Calmar  - Puñal",
            "Nada me Motiva - Puñal",
            "Jipis - Puñal", 

            "Antimilitar - Disolvente",
            "Manipulación genética - Disolvente",
            "Sufre y abstente - Disolvente",
            "Asquerosa policia - Disolvente",
            "Desamortización - Disolvente",
            "Volver a empezar - Disolvente",
            "Ama tus grilletes - Disolvente",
            "Funeral sostenible - Disolvente",
            "Constitucion española - Disolvente",
            "Jóvenes enfermos - Disolvente",
            "Dismaniacxs - Disolvente",
            "Cual será tu destino - Disolvente",
            "Desesperanza - Disolvente",
            "Ser de izquierdas - Disolvente",
            "Censuran - Disolvente",

            "Palermo - KÜKEN",
            "Grass Green - KÜKEN",
            "Split Mind - KÜKEN",
            "Ocean Breeze - KÜKEN",

            "Frontera Francesa - Larsen",
            "Vomitas Sangre - Larsen",
            "Lucha Contra El Techno - Larsen",
            "Nacido de la Pota de un Punk - Larsen",

            "El Juez - Chicharrica",
            "Encerrado - Chicharrica",
            "Quiero Romper - Chicharrica",
            "Defiance - Chicharrica",
            "Es Una Mierda - Chicharrica",
            "Colegas - Chicharrica",
            "El Odio - Chicharrica",
            "Escupiendo - Chicharrica",
            "ETT´s - Chicharrica",
            "Nada Quereis Saber - Chicharrica",
            "La Jaula - Chicharrica",
            "Amanece - Chicharrica",
            "La Calle - Chicharrica",

            "Kärnvapen Attack - Mob 47",  
            "Rustning Är Ett Brott - Mob 47", 
            "Res Dig Mot Överheten - Mob 47",    
            "Vi Rustar Dom Dör - Mob 47",
            "Det Är Upp Till Oss - Mob 47",
            "Dom Ljuger - Mob 47",
            "Ingen Framtid - Mob 47",
            "Animal Liberation - Mob 47",
            "Polisstat - Mob 47",

            "Sistema Siniestro - Ayucaba",
            "¿Quién Dio La Órden? - Aycaba",
            "Óxido - Ayucaba",
            "Pais Aniquilador - Ayucaba",
            "Como te Pudren! - Ayucaba",
            "Operacion Masacre - Ayucaba",
            "Cocaina - Ayucaba",
            "Distancia - Ayucaba",
            "Genocidio por la paz - Ayucaba",
            "Ayucaba- Ayucaba"
          ]
            ,
          [
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A1.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A2.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A3.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A4.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A5.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/A6.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/B1.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/B2.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/B3.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/B4.mp3",
          "https://nervouswreckradio.online/P/ESTIGIA-MAQUETA-CAMINO DEL PROGRESO 1999/B5.mp3",

           "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com.mp3",
            "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com (1).mp3",
            "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com (2).mp3",
            "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com (3).mp3",
            "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com (4).mp3",
            "https://nervouswreckradio.online/P/Supongamos por ejemplo Ataque de Caspa/supongamos-por-ejemplo-ataque-de-caspa-anydownloader.com (5).mp3",

            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com.mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (1).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (2).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (3).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (4).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (5).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (6).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (7).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (8).mp3",
            "https://nervouswreckradio.online/P/Puñal - Buscando la muerte/buscando-la-muerte-puñal-anydownloader.com (9).mp3",

            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%281%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%282%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%283%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%284%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%285%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%286%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%287%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%288%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%289%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%2810%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%2811%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%2812%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%2813%29.mp3",
            "https://nervouswreckradio.online/P/Disolvente%20-%20Maqueta/disolvente-disolvente%20%2814%29.mp3",
            

            "https://nervouswreckradio.online/P/Kuken%20-%20Palermo%20EP/palermo-ep-k%C3%BCken.mp3",
            "https://nervouswreckradio.online/P/Kuken%20-%20Palermo%20EP/palermo-ep-k%C3%BCken%20%281%29.mp3",
            "https://nervouswreckradio.online/P/Kuken%20-%20Palermo%20EP/palermo-ep-k%C3%BCken%20%282%29.mp3",
            "https://nervouswreckradio.online/P/Kuken%20-%20Palermo%20EP/palermo-ep-k%C3%BCken%20%283%29.mp3",

            "https://nervouswreckradio.online/P/larsen%20-%20no/larsen-%C2%A1no-ep-fun-7064-revival-series-5.mp3",
            "https://nervouswreckradio.online/P/larsen%20-%20no/larsen-%C2%A1no-ep-fun-7064-revival-series-5%20%281%29.mp3",
            "https://nervouswreckradio.online/P/larsen%20-%20no/larsen-%C2%A1no-ep-fun-7064-revival-series-5%20%282%29.mp3",
            "https://nervouswreckradio.online/P/larsen%20-%20no/larsen-%C2%A1no-ep-fun-7064-revival-series-5%20%283%29.mp3",

            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/01.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/02.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/03.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/04.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/05.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/06.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/07.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/08.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/09.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/10.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/11.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/12.mp3",
            "https://nervouswreckradio.online/P/2000-QUIERO%20ROMPER/13.mp3",

            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/k%C3%A4rnvapen-attack.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/rustning-%C3%A4r-ett-brott.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/res-dig-mot-%C3%B6verheten.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/vi-rustar-dom-d%C3%B6r.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/det-%C3%A4r-upp-till-oss.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/dom-ljuger.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/ingen-framtid.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/animal-liberation.mp3",
            "https://nervouswreckradio.online/P/Mob%2047%20-%20karnvapen%20attack/polisstat.mp3",

            //Operacion Masacre - Ayucaba

        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%281%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%282%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%283%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%284%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%285%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%286%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%287%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%288%29.mp3",
        "https://nervouswreckradio.online/P/Operacion%20Masacre%20-%20Ayucaba/operaci%C3%B3n-masacre-ayucaba%20%289%29.mp3",


            ],
         [
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",
          "https://nervouswreckradio.online/Img/ESTIGIA-MAQUETA-CAMINO%20DEL%20PROGRESO%201999_400x373.jpg",

          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",
          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",
          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",
          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",
          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",
          "https://nervouswreckradio.online/Img/supongamosAtaquedecaspa.jpg",

          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",
          "https://nervouswreckradio.online/Img/buscandolamuertepu%C3%B1al.jpg",

          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          "https://nervouswreckradio.online/Img/images.png",
          
          "https://nervouswreckradio.online/Img/kuken-palermo.jpg",
          "https://nervouswreckradio.online/Img/kuken-palermo.jpg",
          "https://nervouswreckradio.online/Img/kuken-palermo.jpg",
          "https://nervouswreckradio.online/Img/kuken-palermo.jpg",

          "https://nervouswreckradio.online/Img/larsenno.jpg",
          "https://nervouswreckradio.online/Img/larsenno.jpg",
          "https://nervouswreckradio.online/Img/larsenno.jpg",
          "https://nervouswreckradio.online/Img/larsenno.jpg",

          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",
          "https://nervouswreckradio.online/Img/chicharricaquiero.jpg",

          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",
          "https://nervouswreckradio.online/Img/mob47karnvapenattack.jpg",

          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",
          "https://nervouswreckradio.online/Img/ayucabaoperacion.jpg",

        ],
      ]
