export const surfHour = [

        [
          "Los A-tunes - Atraco a pez espada",
          "Blackball Bandits - Night Of The Vampire",
          "Los Tocadiscos - La cosa",
          "Johnny & the Waves - Battlescar",
          "I Fat Tones - La Sorella Di Christine",
          "Gein and the Graverobbers - Spectre Stomp",
          "LHD - Black Mask",
          "Los Surfistas Basura - Fin de la historia",
          "Los Banditos - Los Banditos",
          "Perro Agradecido - Cum Ea Ita Sint",
          "Pelo Mono - Sonido Amazonico",
          "Robert Johnson and Punchdrunks - Delirium Bullonate",
          "The Obsidians - Notre Histoire",
          "Toro Jones - Night Of The Fly",
          "Urban Zotel & Vid Jamnik - Summer Getaway",
          "Thálasses - ¿Quien Sera?",
          "The Surf Raiders - Rampage",
          "The Spiratones - Coach Surfer (Live)",
          "Die Zorros - Der Lachende Sarg",
          "Bronco Jedson - One Two Three Four",

          "Launch Pad - The Surfites",
          "Comet´s Tail - The Surfites",
          "Space Mover - The Surfites",
          "Moon Buggy - The Surfites",
          "Little Rocket Mill - The Surfites",
          "Rainy Days In Space - The Surfites",
          "Around The Galaxy - The Surfites",
          "Danger Ahead - The Surfites",
          "Space Encounter - The Surfites",
          "Far And Beyond - The Surfites",
          "Marching Robots - The Surfites",
          "Mercurian Surf Stomp - The Surfites",
          "Space Coach - The Surfites",
          "Moon Made - The Surfites",
          "Planetary Stroll - The Surfites",
          "Bonus Track - The Surfites",

          "Speedboat - The Evanstones",
          "London - The Evanstones",
          "Shootup at the OK Canal - The Evanstones",
          "Jojo & the Seven Seas - The Evanstones",
          "The Heat - The Evanstones",
          "El Gato - The Evanstones",
          "The Magnificent Seven - The Evanstones",
          "Eruptors - The Evanstones",
          "Insomnia - The Evanstones",
          "Number Tien - The Evanstones",
          "Alki Stomp - The Evanstones",
          "Island Hopper - The Evanstones",
          "Dead or Facing West - The Evanstones"

        ]
        ,
      [
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com.mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (1).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (2).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (3).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (4).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (5).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (6).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (7).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (8).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (9).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (10).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (11).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (12).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (13).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (14).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (15).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (16).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (17).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (18).mp3",
      "https://nervouswreckradio.online/P/zaybx/zaybx-anydownloader.com (19).mp3",

      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Launch%20Pad_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Comet%27s%20Tail_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Space%20Mover_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Moon%20Buggy_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Little%20Rocket%20Mill_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Rainy%20Days%20In%20Space_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Around%20The%20Galaxy_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Danger%20Ahead_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Space%20Encounter_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Far%20And%20Beyond_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Marching%20Robots_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Mercurian%20Surf%20Stomp_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Space%20Coach_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Moon%20Made_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Planetary%20Stroll_spotdown.org.mp3",
      "https://nervouswreckradio.online/P/Escapades%20From%20Space%20-%20The%20Surfites/Bonus%20Track_spotdown.org.mp3",

      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/speedboat.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/london.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/shootup-at-the-ok-canal.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/jojo-the-seven-seas.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/the-heat.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/el-gato.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/the-magnificent-seven.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/eruptors.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/insomnia.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/number-tien.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/alki-stomp.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/island-hopper.mp3",
      "https://nervouswreckradio.online/P/1961%20The%20Evanstones/dead-or-facing-west.mp3",
      ],

       [
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",
    "https://nervouswreckradio.online/Img/zaybx.jpg",

    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",
    "https://nervouswreckradio.online/Img/surfites-escapades-in-space-LP.jpg",

    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
    "https://nervouswreckradio.online/Img/theevanstones1961.jpg",
      ]
      ];
