export const zorrasAsignaturas = [
        [
        "8 de agosto de 1969 - Zorras Adolescentes",
        "Autopista hacia el cielo - Zorras Adolescentes",
        "El flechazo - Zorras Adolescentes",
        "Fosa comun - Zorras Adolescentes",
        "G.G. Allin - Zorras Adolescentes",
        "Killer man (Gasoline Cover) - Zorras Adolescentes",
        "La habitacion - Zorras Adolescentes",
        "Lluvia de locura - Zorras Adolescentes",
        "Maxwell Smart - Zorras Adolescentes",
        "Mundo mutante - Zorras Adolescentes",
        "Putos Viejos - Zorras Adolescentes",
        "Putridos cuerpos - Zorras Adolescentes",
        "Relación Radioactiva - Zorras Adolescentes",
        "Sade love - Zorras Adolescentes",
        "Todo por amor - Zorras Adolescentes",
        "Un dia de furia - Zorras Adolescentes",
        ],[
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-8-de-agosto-de-1969.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-autopista-hacia-el-cielo.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-el-flechazo.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-fosa-com%C3%BAn.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-g.g-allin.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-killer-man.gasoline-cove.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-la-habitaci%C3%B3n.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-lluvia-de-locura.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-maxwell-smart.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-mundo-mutante.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-putos-viejos.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-putridos-cuerpos.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-relaci%C3%B3n-radioactiva.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-sade-love.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-todo-por-amor.mp3",
          "https://nervouswreckradio.online/P/Zorras%20Adolescentes%20-%20Asignaturas%20Pendientes/zorras-adolescentes-un-d_-a-de-furia.mp3",
      ] 
      ,[
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
        "https://nervouswreckradio.online/Img/zorrasAsignaturas.jpg",
       
        
      ] 
      ];
